/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4-80-gbf87bdd3f6-20210829"
#endif /* AVUTIL_FFVERSION_H */
